version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: monitoring_service
    environment:
      POSTGRES_DB: monitoring_service
      POSTGRES_USER: monitoring
      POSTGRES_PASSWORD: monitoring
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: