spring:
  datasource:
    username: monitoring
    password: monitoring
    url: jdbc:postgresql://localhost:5433/monitoring_service?loggerLevel=OFF

  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
    default-schema: liquibase